name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.x
          cache-prefix: ${{ runner.os }}-opam-ocaml-4.14.x
          opam-repositories: |
            default: https://opam.ocaml.org

      - name: Cache OPAM dependencies
        id: cache-opam
        uses: actions/cache@v3
        with:
          path: ~/.opam
          key: ${{ runner.os }}-opam-ocaml-4.14.x

      - name: Dependencies
        if: steps.cache-opam.outputs.cache-hit != 'true'
        run: |
          opam install dune alcotest zanuda

      - name: Build
        run: |
          eval $(opam env)
          dune build @check

      - name: Run tests
        run: |
          eval $(opam env)
          dune runtest

      - name: Run linter
        run: |
          eval $(opam env)
          zanuda -dir .      